spring.application.name=jobflow

spring.datasource.url=jdbc:postgresql://localhost:5432/jobflow
spring.datasource.username=jobflow
spring.datasource.password=jobflow

spring.jpa.hibernate.ddl-auto=update